/*
 * SPDX-License-Identifier: GPL-2.0-only
 */
// Reference data for the RISC-V manual tab. It covers what ASE Studio builds
// for (rv32ima + F/D + C + Zicsr + Zifencei), the assembler pseudo-instructions
// and the common GNU assembler directives. The descriptions are original
// summaries written for students; the RISC-V ISA specification is the
// authoritative source.
//
// Encodings list the fixed bits of each field; fields left out are operands.
// Pseudo-instructions and compressed instructions list the base instructions
// they stand for in `expansion` instead.
const RISCV_MANUAL = (() => {
  const OP = "0110011", OP_IMM = "0010011", LOAD = "0000011", STORE = "0100011",
    BRANCH = "1100011", SYSTEM = "1110011", AMO = "0101111", OP_FP = "1010011";
  const r = (funct7, funct3, opcode = OP) => ({format: "R", funct7, funct3, opcode});
  const i = (funct3, opcode = OP_IMM) => ({format: "I", funct3, opcode});
  const shift = (funct7, funct3) => ({format: "I-shamt", funct7, funct3, opcode: OP_IMM});
  const s = funct3 => ({format: "S", funct3, opcode: STORE});
  const b = funct3 => ({format: "B", funct3, opcode: BRANCH});
  const csr = funct3 => ({format: "I-csr", funct3, opcode: SYSTEM});
  const amo = (funct5, extra = {}) => ({format: "R-atomic", funct5, funct3: "010", opcode: AMO, ...extra});
  // Floating-point R-type: funct7 = funct5 followed by the 2-bit format (00 = S, 01 = D).
  const fp = (funct5, precision, extra = {}) => ({
    format: "R", funct7: funct5 + (precision === "d" ? "01" : "00"), funct3: "rm", opcode: OP_FP, ...extra
  });
  const fma = (opcode, precision) => ({format: "R4", fmt: precision === "d" ? "01" : "00", funct3: "rm", opcode});

  const entries = [
    // ---- RV32I: upper immediates and jumps ----
    {mnemonic: "lui", extension: "RV32I", syntax: "lui rd, imm", name: "Load upper immediate",
      operation: "rd ← imm << 12",
      description: "Places the 20-bit immediate in bits 31–12 of rd and clears the low 12 bits. Together with addi it builds any 32-bit constant, which is what the li pseudo-instruction does for you.",
      example: "lui t0, 0x12345      # t0 = 0x12345000",
      encoding: {format: "U", opcode: "0110111"}, see: ["li", "auipc", "addi"]},
    {mnemonic: "auipc", extension: "RV32I", syntax: "auipc rd, imm", name: "Add upper immediate to PC",
      operation: "rd ← pc + (imm << 12)",
      description: "Adds the 20-bit immediate, shifted left by 12, to the address of this instruction. It is the first half of PC-relative addressing used by la, call and loads from a symbol.",
      example: "auipc t0, 0          # t0 = address of this instruction",
      encoding: {format: "U", opcode: "0010111"}, see: ["la", "call", "lui"]},
    {mnemonic: "jal", extension: "RV32I", syntax: "jal rd, label", name: "Jump and link",
      operation: "rd ← pc + 4\npc ← pc + offset",
      description: "Jumps to a PC-relative target within ±1 MiB and stores the return address in rd. Use rd = ra for a function call; with rd = x0 it is a plain jump (the j pseudo-instruction). Writing just `jal label` means `jal ra, label`.",
      example: "jal ra, compute      # call compute, return address in ra",
      encoding: {format: "J", opcode: "1101111"}, see: ["jalr", "j", "call", "ret"]},
    {mnemonic: "jalr", extension: "RV32I", syntax: "jalr rd, offset(rs1)", name: "Jump and link register",
      operation: "t ← pc + 4\npc ← (rs1 + sext(offset)) & ~1\nrd ← t",
      description: "Jumps to the address in rs1 plus a 12-bit signed offset (the lowest bit is cleared) and stores the return address in rd. It is used for returns (ret), calls through a pointer and jump tables.",
      example: "jalr x0, 0(ra)       # return (same as ret)",
      encoding: i("000", "1100111"), see: ["jal", "jr", "ret"]},

    // ---- RV32I: branches ----
    {mnemonic: "beq", extension: "RV32I", syntax: "beq rs1, rs2, label", name: "Branch if equal",
      operation: "if rs1 == rs2: pc ← pc + offset",
      description: "Branches to a PC-relative target within ±4 KiB when the two registers are equal.",
      example: "beq t0, t1, done", encoding: b("000"), see: ["bne", "beqz"]},
    {mnemonic: "bne", extension: "RV32I", syntax: "bne rs1, rs2, label", name: "Branch if not equal",
      operation: "if rs1 ≠ rs2: pc ← pc + offset",
      description: "Branches to a PC-relative target within ±4 KiB when the two registers differ. A common loop-closing branch.",
      example: "bne t0, zero, loop", encoding: b("001"), see: ["beq", "bnez"]},
    {mnemonic: "blt", extension: "RV32I", syntax: "blt rs1, rs2, label", name: "Branch if less than",
      operation: "if rs1 <s rs2: pc ← pc + offset",
      description: "Branches when rs1 is less than rs2, comparing them as signed two's-complement numbers. For unsigned values use bltu.",
      example: "blt a0, a1, smaller", encoding: b("100"), see: ["bltu", "bgt", "bltz"]},
    {mnemonic: "bge", extension: "RV32I", syntax: "bge rs1, rs2, label", name: "Branch if greater or equal",
      operation: "if rs1 ≥s rs2: pc ← pc + offset",
      description: "Branches when rs1 is greater than or equal to rs2 as signed numbers. For unsigned values use bgeu.",
      example: "bge t0, t1, exit", encoding: b("101"), see: ["bgeu", "ble", "bgez"]},
    {mnemonic: "bltu", extension: "RV32I", syntax: "bltu rs1, rs2, label", name: "Branch if less than, unsigned",
      operation: "if rs1 <u rs2: pc ← pc + offset",
      description: "Branches when rs1 is less than rs2, comparing them as unsigned numbers. Useful for addresses and array bounds checks.",
      example: "bltu t0, t1, in_range", encoding: b("110"), see: ["blt", "bgtu"]},
    {mnemonic: "bgeu", extension: "RV32I", syntax: "bgeu rs1, rs2, label", name: "Branch if greater or equal, unsigned",
      operation: "if rs1 ≥u rs2: pc ← pc + offset",
      description: "Branches when rs1 is greater than or equal to rs2 as unsigned numbers.",
      example: "bgeu t0, t1, out_of_range", encoding: b("111"), see: ["bge", "bleu"]},

    // ---- RV32I: loads and stores ----
    {mnemonic: "lb", extension: "RV32I", syntax: "lb rd, offset(rs1)", name: "Load byte",
      operation: "rd ← sext(M[rs1 + sext(offset)][7:0])",
      description: "Loads one byte and sign-extends it to 32 bits. The offset is a 12-bit signed constant (−2048 to 2047).",
      example: "lb t0, 0(a0)", encoding: i("000", LOAD), see: ["lbu", "sb"]},
    {mnemonic: "lh", extension: "RV32I", syntax: "lh rd, offset(rs1)", name: "Load halfword",
      operation: "rd ← sext(M[rs1 + sext(offset)][15:0])",
      description: "Loads a 16-bit halfword and sign-extends it to 32 bits. The address should be 2-byte aligned.",
      example: "lh t0, 2(a0)", encoding: i("001", LOAD), see: ["lhu", "sh"]},
    {mnemonic: "lw", extension: "RV32I", syntax: "lw rd, offset(rs1)", name: "Load word",
      operation: "rd ← M[rs1 + sext(offset)][31:0]",
      description: "Loads a 32-bit word. The address should be 4-byte aligned. The assembler also accepts `lw rd, symbol`, which expands to auipc + lw.",
      example: "lw t0, 8(sp)", encoding: i("010", LOAD), see: ["sw", "lb", "lh"]},
    {mnemonic: "lbu", extension: "RV32I", syntax: "lbu rd, offset(rs1)", name: "Load byte, unsigned",
      operation: "rd ← zext(M[rs1 + sext(offset)][7:0])",
      description: "Loads one byte and fills the upper 24 bits with zeros. Use it for characters and unsigned byte arrays.",
      example: "lbu t0, 0(a0)        # next character of a string", encoding: i("100", LOAD), see: ["lb"]},
    {mnemonic: "lhu", extension: "RV32I", syntax: "lhu rd, offset(rs1)", name: "Load halfword, unsigned",
      operation: "rd ← zext(M[rs1 + sext(offset)][15:0])",
      description: "Loads a 16-bit halfword and fills the upper 16 bits with zeros.",
      example: "lhu t0, 0(a0)", encoding: i("101", LOAD), see: ["lh"]},
    {mnemonic: "sb", extension: "RV32I", syntax: "sb rs2, offset(rs1)", name: "Store byte",
      operation: "M[rs1 + sext(offset)] ← rs2[7:0]",
      description: "Stores the lowest byte of rs2. Note the operand order: the value comes first, the address second.",
      example: "sb t0, 0(a0)", encoding: s("000"), see: ["lb", "lbu"]},
    {mnemonic: "sh", extension: "RV32I", syntax: "sh rs2, offset(rs1)", name: "Store halfword",
      operation: "M[rs1 + sext(offset)] ← rs2[15:0]",
      description: "Stores the lowest 16 bits of rs2. The address should be 2-byte aligned.",
      example: "sh t0, 2(a0)", encoding: s("001"), see: ["lh", "lhu"]},
    {mnemonic: "sw", extension: "RV32I", syntax: "sw rs2, offset(rs1)", name: "Store word",
      operation: "M[rs1 + sext(offset)] ← rs2[31:0]",
      description: "Stores the 32-bit value of rs2. The address should be 4-byte aligned. `sw rs2, symbol, rt` stores to a symbol using rt as a scratch register.",
      example: "sw ra, 12(sp)", encoding: s("010"), see: ["lw"]},

    // ---- RV32I: register-immediate arithmetic ----
    {mnemonic: "addi", extension: "RV32I", syntax: "addi rd, rs1, imm", name: "Add immediate",
      operation: "rd ← rs1 + sext(imm)",
      description: "Adds a 12-bit signed constant (−2048 to 2047). Overflow wraps around silently. There is no subi: add a negative immediate instead. For larger constants use li.",
      example: "addi sp, sp, -16     # reserve 16 bytes of stack", encoding: i("000"), see: ["add", "li", "mv"]},
    {mnemonic: "slti", extension: "RV32I", syntax: "slti rd, rs1, imm", name: "Set if less than immediate",
      operation: "rd ← (rs1 <s sext(imm)) ? 1 : 0",
      description: "Writes 1 to rd when rs1 is less than the immediate as signed numbers, otherwise 0.",
      example: "slti t0, a0, 10", encoding: i("010"), see: ["slt", "sltiu"]},
    {mnemonic: "sltiu", extension: "RV32I", syntax: "sltiu rd, rs1, imm", name: "Set if less than immediate, unsigned",
      operation: "rd ← (rs1 <u sext(imm)) ? 1 : 0",
      description: "Like slti, but compares as unsigned numbers. The immediate is still sign-extended first. `sltiu rd, rs1, 1` sets rd when rs1 is zero (the seqz pseudo-instruction).",
      example: "sltiu t0, a0, 1      # t0 = (a0 == 0)", encoding: i("011"), see: ["seqz", "sltu"]},
    {mnemonic: "xori", extension: "RV32I", syntax: "xori rd, rs1, imm", name: "XOR immediate",
      operation: "rd ← rs1 ^ sext(imm)",
      description: "Bitwise exclusive OR with a sign-extended 12-bit constant. `xori rd, rs1, -1` inverts every bit (the not pseudo-instruction).",
      example: "xori t0, t0, 1       # toggle bit 0", encoding: i("100"), see: ["xor", "not"]},
    {mnemonic: "ori", extension: "RV32I", syntax: "ori rd, rs1, imm", name: "OR immediate",
      operation: "rd ← rs1 | sext(imm)",
      description: "Bitwise OR with a sign-extended 12-bit constant. Useful to set bits.",
      example: "ori t0, t0, 0x10     # set bit 4", encoding: i("110"), see: ["or"]},
    {mnemonic: "andi", extension: "RV32I", syntax: "andi rd, rs1, imm", name: "AND immediate",
      operation: "rd ← rs1 & sext(imm)",
      description: "Bitwise AND with a sign-extended 12-bit constant. Useful to mask or test bits.",
      example: "andi t0, a0, 1       # t0 = a0 is odd", encoding: i("111"), see: ["and", "zext.b"]},
    {mnemonic: "slli", extension: "RV32I", syntax: "slli rd, rs1, shamt", name: "Shift left logical immediate",
      operation: "rd ← rs1 << shamt",
      description: "Shifts left by a constant from 0 to 31, filling with zeros. Shifting by n multiplies by 2ⁿ, which is the usual way to turn an array index into a byte offset.",
      example: "slli t0, t1, 2       # t0 = t1 * 4", encoding: shift("0000000", "001"), see: ["sll", "srli", "srai"]},
    {mnemonic: "srli", extension: "RV32I", syntax: "srli rd, rs1, shamt", name: "Shift right logical immediate",
      operation: "rd ← rs1 >>u shamt",
      description: "Shifts right by a constant from 0 to 31, filling with zeros. Divides unsigned values by 2ⁿ.",
      example: "srli t0, t1, 1", encoding: shift("0000000", "101"), see: ["srl", "srai", "slli"]},
    {mnemonic: "srai", extension: "RV32I", syntax: "srai rd, rs1, shamt", name: "Shift right arithmetic immediate",
      operation: "rd ← rs1 >>s shamt",
      description: "Shifts right by a constant from 0 to 31, copying the sign bit into the vacated bits. Divides signed values by 2ⁿ, rounding towards −∞.",
      example: "srai t0, t1, 4", encoding: shift("0100000", "101"), see: ["sra", "srli", "slli"]},

    // ---- RV32I: register-register arithmetic ----
    {mnemonic: "add", extension: "RV32I", syntax: "add rd, rs1, rs2", name: "Add",
      operation: "rd ← rs1 + rs2",
      description: "Adds two registers. Overflow wraps around silently: RISC-V has no overflow flag.",
      example: "add a0, a0, a1", encoding: r("0000000", "000"), see: ["addi", "sub"]},
    {mnemonic: "sub", extension: "RV32I", syntax: "sub rd, rs1, rs2", name: "Subtract",
      operation: "rd ← rs1 − rs2",
      description: "Subtracts rs2 from rs1. Overflow wraps around silently.",
      example: "sub t0, t1, t2", encoding: r("0100000", "000"), see: ["add", "neg"]},
    {mnemonic: "sll", extension: "RV32I", syntax: "sll rd, rs1, rs2", name: "Shift left logical",
      operation: "rd ← rs1 << rs2[4:0]",
      description: "Shifts left by the amount in the low 5 bits of rs2, filling with zeros.",
      example: "sll t0, t1, t2", encoding: r("0000000", "001"), see: ["slli"]},
    {mnemonic: "slt", extension: "RV32I", syntax: "slt rd, rs1, rs2", name: "Set if less than",
      operation: "rd ← (rs1 <s rs2) ? 1 : 0",
      description: "Writes 1 to rd when rs1 is less than rs2 as signed numbers, otherwise 0.",
      example: "slt t0, a0, a1", encoding: r("0000000", "010"), see: ["sltu", "slti", "sltz", "sgtz"]},
    {mnemonic: "sltu", extension: "RV32I", syntax: "sltu rd, rs1, rs2", name: "Set if less than, unsigned",
      operation: "rd ← (rs1 <u rs2) ? 1 : 0",
      description: "Writes 1 to rd when rs1 is less than rs2 as unsigned numbers. `sltu rd, x0, rs2` sets rd when rs2 is not zero (snez).",
      example: "sltu t0, a0, a1", encoding: r("0000000", "011"), see: ["slt", "snez"]},
    {mnemonic: "xor", extension: "RV32I", syntax: "xor rd, rs1, rs2", name: "Exclusive OR",
      operation: "rd ← rs1 ^ rs2",
      description: "Bitwise exclusive OR of two registers.",
      example: "xor t0, t1, t2", encoding: r("0000000", "100"), see: ["xori"]},
    {mnemonic: "srl", extension: "RV32I", syntax: "srl rd, rs1, rs2", name: "Shift right logical",
      operation: "rd ← rs1 >>u rs2[4:0]",
      description: "Shifts right by the amount in the low 5 bits of rs2, filling with zeros.",
      example: "srl t0, t1, t2", encoding: r("0000000", "101"), see: ["srli", "sra"]},
    {mnemonic: "sra", extension: "RV32I", syntax: "sra rd, rs1, rs2", name: "Shift right arithmetic",
      operation: "rd ← rs1 >>s rs2[4:0]",
      description: "Shifts right by the amount in the low 5 bits of rs2, copying the sign bit into the vacated bits.",
      example: "sra t0, t1, t2", encoding: r("0100000", "101"), see: ["srai", "srl"]},
    {mnemonic: "or", extension: "RV32I", syntax: "or rd, rs1, rs2", name: "OR",
      operation: "rd ← rs1 | rs2",
      description: "Bitwise OR of two registers.",
      example: "or t0, t1, t2", encoding: r("0000000", "110"), see: ["ori"]},
    {mnemonic: "and", extension: "RV32I", syntax: "and rd, rs1, rs2", name: "AND",
      operation: "rd ← rs1 & rs2",
      description: "Bitwise AND of two registers.",
      example: "and t0, t1, t2", encoding: r("0000000", "111"), see: ["andi"]},

    // ---- RV32I: system ----
    {mnemonic: "fence", extension: "RV32I", syntax: "fence [pred, succ]", name: "Memory fence",
      operation: "order memory and I/O accesses",
      description: "Orders memory accesses: those of kinds `pred` (any of i, o, r, w) before the fence complete before those of kinds `succ` after it. Plain `fence` means `fence iorw, iorw`. A single-core program normally does not need it.",
      example: "fence rw, rw", encoding: {format: "I-fence", funct3: "000", opcode: "0001111"}, system: true},
    {mnemonic: "ecall", extension: "RV32I", syntax: "ecall", name: "Environment call",
      operation: "request a service from the environment",
      description: "Asks the execution environment for a service. Under gem5 syscall emulation the Linux convention applies: the service number goes in a7, arguments in a0–a5, and the result comes back in a0. a7 = 93 exits with status a0 (that is what the End block does); a7 = 64 is write(fd, buffer, length).",
      example: "li a0, 0\nli a7, 93\necall                # exit(0)",
      encoding: {format: "I", imm: "000000000000", rs1: "00000", funct3: "000", rd: "00000", opcode: SYSTEM}, system: true},
    {mnemonic: "ebreak", extension: "RV32I", syntax: "ebreak", name: "Environment break",
      operation: "transfer control to a debugger",
      description: "Raises a breakpoint exception so a debugger can take over.",
      example: "ebreak",
      encoding: {format: "I", imm: "000000000001", rs1: "00000", funct3: "000", rd: "00000", opcode: SYSTEM}, system: true},

    // ---- Zifencei ----
    {mnemonic: "fence.i", extension: "Zifencei", syntax: "fence.i", name: "Instruction fence",
      operation: "synchronize instruction fetches with earlier stores",
      description: "Makes stores that come before it visible to the instruction fetches that come after it. Only needed by self-modifying code or code that writes instructions to memory.",
      example: "fence.i", encoding: {format: "I", imm: "000000000000", rs1: "00000", funct3: "001", rd: "00000", opcode: "0001111"}, system: true},

    // ---- Zicsr ----
    {mnemonic: "csrrw", extension: "Zicsr", syntax: "csrrw rd, csr, rs1", name: "CSR read and write",
      operation: "t ← CSR[csr]\nCSR[csr] ← rs1\nrd ← t",
      description: "Atomically swaps a control and status register with rs1. With rd = x0 the CSR is not read (csrw).",
      example: "csrrw t0, fcsr, t1", encoding: csr("001"), see: ["csrw", "csrrs"]},
    {mnemonic: "csrrs", extension: "Zicsr", syntax: "csrrs rd, csr, rs1", name: "CSR read and set bits",
      operation: "t ← CSR[csr]\nCSR[csr] ← t | rs1\nrd ← t",
      description: "Reads a CSR and sets the bits that are 1 in rs1. With rs1 = x0 it only reads, which is what csrr, rdcycle and rdinstret use.",
      example: "csrrs t0, cycle, x0  # read the cycle counter", encoding: csr("010"), see: ["csrr", "rdcycle"]},
    {mnemonic: "csrrc", extension: "Zicsr", syntax: "csrrc rd, csr, rs1", name: "CSR read and clear bits",
      operation: "t ← CSR[csr]\nCSR[csr] ← t & ~rs1\nrd ← t",
      description: "Reads a CSR and clears the bits that are 1 in rs1.",
      example: "csrrc t0, fflags, t1", encoding: csr("011"), see: ["csrc"]},
    {mnemonic: "csrrwi", extension: "Zicsr", syntax: "csrrwi rd, csr, uimm", name: "CSR read and write immediate",
      operation: "rd ← CSR[csr]\nCSR[csr] ← zext(uimm)",
      description: "Like csrrw with a 5-bit unsigned constant (0–31) instead of a register.",
      example: "csrrwi t0, frm, 1", encoding: csr("101"), see: ["csrwi"]},
    {mnemonic: "csrrsi", extension: "Zicsr", syntax: "csrrsi rd, csr, uimm", name: "CSR read and set bits immediate",
      operation: "rd ← CSR[csr]\nCSR[csr] ← CSR[csr] | zext(uimm)",
      description: "Like csrrs with a 5-bit unsigned constant instead of a register.",
      example: "csrrsi t0, fflags, 1", encoding: csr("110"), see: ["csrsi"]},
    {mnemonic: "csrrci", extension: "Zicsr", syntax: "csrrci rd, csr, uimm", name: "CSR read and clear bits immediate",
      operation: "rd ← CSR[csr]\nCSR[csr] ← CSR[csr] & ~zext(uimm)",
      description: "Like csrrc with a 5-bit unsigned constant instead of a register.",
      example: "csrrci t0, fflags, 31", encoding: csr("111"), see: ["csrci"]},

    // ---- Privileged ----
    {mnemonic: "mret", extension: "Privileged", syntax: "mret", name: "Return from machine-mode trap",
      operation: "pc ← mepc; restore the privilege mode from mstatus",
      description: "Returns from a machine-mode trap handler. Programs in ASE Studio run as user programs under gem5 syscall emulation, so you will not normally use it.",
      example: "mret", encoding: {format: "R", funct7: "0011000", rs2: "00010", rs1: "00000", funct3: "000", rd: "00000", opcode: SYSTEM}, system: true},
    {mnemonic: "wfi", extension: "Privileged", syntax: "wfi", name: "Wait for interrupt",
      operation: "stall until an interrupt may need servicing",
      description: "Hints that the hart can sleep until an interrupt arrives. Not useful in user programs.",
      example: "wfi", encoding: {format: "R", funct7: "0001000", rs2: "00101", rs1: "00000", funct3: "000", rd: "00000", opcode: SYSTEM}, system: true},

    // ---- M: multiply and divide ----
    {mnemonic: "mul", extension: "M", syntax: "mul rd, rs1, rs2", name: "Multiply",
      operation: "rd ← (rs1 × rs2)[31:0]",
      description: "Multiplies two registers and keeps the low 32 bits. The low half is the same for signed and unsigned operands.",
      example: "mul t0, t1, t2", encoding: r("0000001", "000"), see: ["mulh", "mulhu"]},
    {mnemonic: "mulh", extension: "M", syntax: "mulh rd, rs1, rs2", name: "Multiply high, signed",
      operation: "rd ← (sext(rs1) × sext(rs2))[63:32]",
      description: "Returns the upper 32 bits of the 64-bit product of two signed values. Use it after mul to get the full product.",
      example: "mulh t0, t1, t2", encoding: r("0000001", "001"), see: ["mul", "mulhu", "mulhsu"]},
    {mnemonic: "mulhsu", extension: "M", syntax: "mulhsu rd, rs1, rs2", name: "Multiply high, signed × unsigned",
      operation: "rd ← (sext(rs1) × zext(rs2))[63:32]",
      description: "Returns the upper 32 bits of the product of signed rs1 and unsigned rs2.",
      example: "mulhsu t0, t1, t2", encoding: r("0000001", "010"), see: ["mulh", "mulhu"]},
    {mnemonic: "mulhu", extension: "M", syntax: "mulhu rd, rs1, rs2", name: "Multiply high, unsigned",
      operation: "rd ← (zext(rs1) × zext(rs2))[63:32]",
      description: "Returns the upper 32 bits of the 64-bit product of two unsigned values.",
      example: "mulhu t0, t1, t2", encoding: r("0000001", "011"), see: ["mul", "mulh"]},
    {mnemonic: "div", extension: "M", syntax: "div rd, rs1, rs2", name: "Divide, signed",
      operation: "rd ← rs1 ÷s rs2   (rounded towards zero)",
      description: "Signed division, rounded towards zero. It never traps: dividing by zero returns −1, and −2³¹ ÷ −1 returns −2³¹.",
      example: "div t0, t1, t2", encoding: r("0000001", "100"), see: ["rem", "divu"]},
    {mnemonic: "divu", extension: "M", syntax: "divu rd, rs1, rs2", name: "Divide, unsigned",
      operation: "rd ← rs1 ÷u rs2",
      description: "Unsigned division. Dividing by zero returns 2³² − 1 (all bits set) without trapping.",
      example: "divu t0, t1, t2", encoding: r("0000001", "101"), see: ["remu", "div"]},
    {mnemonic: "rem", extension: "M", syntax: "rem rd, rs1, rs2", name: "Remainder, signed",
      operation: "rd ← rs1 mod rs2   (sign of rs1)",
      description: "Remainder of the signed division; the result has the sign of the dividend. Dividing by zero returns rs1; −2³¹ rem −1 returns 0.",
      example: "rem t0, a0, a1", encoding: r("0000001", "110"), see: ["div", "remu"]},
    {mnemonic: "remu", extension: "M", syntax: "remu rd, rs1, rs2", name: "Remainder, unsigned",
      operation: "rd ← rs1 mod rs2   (unsigned)",
      description: "Remainder of the unsigned division. Dividing by zero returns rs1.",
      example: "remu t0, a0, a1", encoding: r("0000001", "111"), see: ["divu", "rem"]},

    // ---- A: atomics ----
    {mnemonic: "lr.w", extension: "A", syntax: "lr.w rd, (rs1)", name: "Load reserved word",
      operation: "rd ← M[rs1]; reserve the address",
      description: "Loads a word and registers a reservation on its address. A later sc.w to the same address succeeds only if nothing else wrote it in between. Append .aq / .rl / .aqrl for ordering.",
      example: "retry:\n    lr.w t0, (a0)\n    addi t0, t0, 1\n    sc.w t1, t0, (a0)\n    bnez t1, retry",
      encoding: amo("00010", {rs2: "00000"}), see: ["sc.w"]},
    {mnemonic: "sc.w", extension: "A", syntax: "sc.w rd, rs2, (rs1)", name: "Store conditional word",
      operation: "if reservation valid: M[rs1] ← rs2, rd ← 0\nelse: rd ← nonzero",
      description: "Stores rs2 only if the reservation from the matching lr.w still holds. rd is 0 on success and nonzero on failure, so it is usually followed by bnez back to the retry point.",
      example: "sc.w t1, t0, (a0)", encoding: amo("00011"), see: ["lr.w"]},
    ...[
      ["amoswap.w", "00001", "Atomic swap", "rs2", "Atomically swaps memory with rs2. Useful for simple locks."],
      ["amoadd.w", "00000", "Atomic add", "t + rs2", "Atomically adds rs2 to the word in memory."],
      ["amoxor.w", "00100", "Atomic XOR", "t ^ rs2", "Atomically XORs rs2 into the word in memory."],
      ["amoand.w", "01100", "Atomic AND", "t & rs2", "Atomically ANDs rs2 into the word in memory."],
      ["amoor.w", "01000", "Atomic OR", "t | rs2", "Atomically ORs rs2 into the word in memory."],
      ["amomin.w", "10000", "Atomic minimum, signed", "min_s(t, rs2)", "Atomically stores the signed minimum of memory and rs2."],
      ["amomax.w", "10100", "Atomic maximum, signed", "max_s(t, rs2)", "Atomically stores the signed maximum of memory and rs2."],
      ["amominu.w", "11000", "Atomic minimum, unsigned", "min_u(t, rs2)", "Atomically stores the unsigned minimum of memory and rs2."],
      ["amomaxu.w", "11100", "Atomic maximum, unsigned", "max_u(t, rs2)", "Atomically stores the unsigned maximum of memory and rs2."]
    ].map(([mnemonic, funct5, name, result, description]) => ({
      mnemonic, extension: "A", syntax: `${mnemonic} rd, rs2, (rs1)`, name,
      operation: `t ← M[rs1]\nM[rs1] ← ${result}\nrd ← t`,
      description: description + " rd receives the old value. Append .aq / .rl / .aqrl for ordering.",
      example: `${mnemonic} t0, t1, (a0)`, encoding: amo(funct5)
    })),

    // ---- F and D: loads and stores ----
    {mnemonic: "flw", extension: "F", syntax: "flw rd, offset(rs1)", name: "Load single-precision float",
      operation: "f[rd] ← M[rs1 + sext(offset)][31:0]",
      description: "Loads a 32-bit float into a floating-point register. The base address is an integer register.",
      example: "flw ft0, 0(a0)", encoding: {format: "I", funct3: "010", opcode: "0000111"}, see: ["fsw", "fld"]},
    {mnemonic: "fsw", extension: "F", syntax: "fsw rs2, offset(rs1)", name: "Store single-precision float",
      operation: "M[rs1 + sext(offset)] ← f[rs2][31:0]",
      description: "Stores a 32-bit float from a floating-point register. The base address is an integer register.",
      example: "fsw ft0, 4(a0)", encoding: {format: "S", funct3: "010", opcode: "0100111"}, see: ["flw", "fsd"]},
    {mnemonic: "fld", extension: "D", syntax: "fld rd, offset(rs1)", name: "Load double-precision float",
      operation: "f[rd] ← M[rs1 + sext(offset)][63:0]",
      description: "Loads a 64-bit double into a floating-point register. The address should be 8-byte aligned.",
      example: "fld ft0, 0(a0)", encoding: {format: "I", funct3: "011", opcode: "0000111"}, see: ["fsd", "flw"]},
    {mnemonic: "fsd", extension: "D", syntax: "fsd rs2, offset(rs1)", name: "Store double-precision float",
      operation: "M[rs1 + sext(offset)] ← f[rs2][63:0]",
      description: "Stores a 64-bit double from a floating-point register. The address should be 8-byte aligned.",
      example: "fsd ft0, 8(a0)", encoding: {format: "S", funct3: "011", opcode: "0100111"}, see: ["fld", "fsw"]},

    // ---- F: moves between register files ----
    {mnemonic: "fmv.x.w", extension: "F", syntax: "fmv.x.w rd, rs1", name: "Move float bits to integer register",
      operation: "x[rd] ← f[rs1][31:0]",
      description: "Copies the raw bit pattern of a single-precision register into an integer register without converting it: 1.0 becomes 0x3F800000. To convert the value use fcvt.w.s.",
      example: "fmv.x.w t0, ft0", encoding: fp("11100", "s", {rs2: "00000", funct3: "000"}), see: ["fmv.w.x", "fcvt.w.s"]},
    {mnemonic: "fmv.w.x", extension: "F", syntax: "fmv.w.x rd, rs1", name: "Move integer bits to float register",
      operation: "f[rd] ← x[rs1][31:0]",
      description: "Copies the raw bit pattern of an integer register into a single-precision register without converting it. To convert an integer value use fcvt.s.w.",
      example: "fmv.w.x ft0, zero    # ft0 = 0.0", encoding: fp("11110", "s", {rs2: "00000", funct3: "000"}), see: ["fmv.x.w", "fcvt.s.w"]},

    // ---- F: fused multiply-add ----
    ...floatFamily(precision => [
      {mnemonic: `fmadd.${precision}`, syntax: `fmadd.${precision} rd, rs1, rs2, rs3`, name: "Fused multiply-add",
        operation: "f[rd] ← f[rs1] × f[rs2] + f[rs3]",
        description: "Multiplies and adds with a single rounding at the end, which is more accurate than fmul followed by fadd.",
        example: `fmadd.${precision} fa0, fa1, fa2, fa0   # fa0 += fa1 * fa2`, encoding: fma("1000011", precision)},
      {mnemonic: `fmsub.${precision}`, syntax: `fmsub.${precision} rd, rs1, rs2, rs3`, name: "Fused multiply-subtract",
        operation: "f[rd] ← f[rs1] × f[rs2] − f[rs3]",
        description: "Multiplies and subtracts rs3 with a single rounding at the end.",
        example: `fmsub.${precision} fa0, fa1, fa2, fa3`, encoding: fma("1000111", precision)},
      {mnemonic: `fnmsub.${precision}`, syntax: `fnmsub.${precision} rd, rs1, rs2, rs3`, name: "Fused negative multiply-subtract",
        operation: "f[rd] ← −(f[rs1] × f[rs2]) + f[rs3]",
        description: "Negates the product and adds rs3, with a single rounding at the end.",
        example: `fnmsub.${precision} fa0, fa1, fa2, fa3`, encoding: fma("1001011", precision)},
      {mnemonic: `fnmadd.${precision}`, syntax: `fnmadd.${precision} rd, rs1, rs2, rs3`, name: "Fused negative multiply-add",
        operation: "f[rd] ← −(f[rs1] × f[rs2]) − f[rs3]",
        description: "Negates the product and subtracts rs3, with a single rounding at the end.",
        example: `fnmadd.${precision} fa0, fa1, fa2, fa3`, encoding: fma("1001111", precision)}
    ]),

    // ---- F and D: arithmetic, sign injection, compare, classify ----
    ...floatFamily((precision, label) => [
      {mnemonic: `fadd.${precision}`, syntax: `fadd.${precision} rd, rs1, rs2`, name: `Add, ${label}`,
        operation: "f[rd] ← f[rs1] + f[rs2]",
        description: "Adds two floating-point registers, rounding with the current rounding mode (round to nearest, ties to even, by default).",
        example: `fadd.${precision} fa0, fa0, fa1`, encoding: fp("00000", precision)},
      {mnemonic: `fsub.${precision}`, syntax: `fsub.${precision} rd, rs1, rs2`, name: `Subtract, ${label}`,
        operation: "f[rd] ← f[rs1] − f[rs2]",
        description: "Subtracts rs2 from rs1.",
        example: `fsub.${precision} fa0, fa0, fa1`, encoding: fp("00001", precision)},
      {mnemonic: `fmul.${precision}`, syntax: `fmul.${precision} rd, rs1, rs2`, name: `Multiply, ${label}`,
        operation: "f[rd] ← f[rs1] × f[rs2]",
        description: "Multiplies two floating-point registers.",
        example: `fmul.${precision} fa0, fa0, fa1`, encoding: fp("00010", precision)},
      {mnemonic: `fdiv.${precision}`, syntax: `fdiv.${precision} rd, rs1, rs2`, name: `Divide, ${label}`,
        operation: "f[rd] ← f[rs1] ÷ f[rs2]",
        description: "Divides rs1 by rs2. Dividing a nonzero value by zero gives ±∞ and sets the divide-by-zero flag; it does not trap.",
        example: `fdiv.${precision} fa0, fa0, fa1`, encoding: fp("00011", precision)},
      {mnemonic: `fsqrt.${precision}`, syntax: `fsqrt.${precision} rd, rs1`, name: `Square root, ${label}`,
        operation: "f[rd] ← √f[rs1]",
        description: "Square root. A negative operand gives NaN and sets the invalid-operation flag.",
        example: `fsqrt.${precision} fa0, fa0`, encoding: fp("01011", precision, {rs2: "00000"})},
      {mnemonic: `fmin.${precision}`, syntax: `fmin.${precision} rd, rs1, rs2`, name: `Minimum, ${label}`,
        operation: "f[rd] ← min(f[rs1], f[rs2])",
        description: "Smaller of the two values. If only one operand is NaN the other one is returned; −0.0 counts as smaller than +0.0.",
        example: `fmin.${precision} fa0, fa0, fa1`, encoding: fp("00101", precision, {funct3: "000"})},
      {mnemonic: `fmax.${precision}`, syntax: `fmax.${precision} rd, rs1, rs2`, name: `Maximum, ${label}`,
        operation: "f[rd] ← max(f[rs1], f[rs2])",
        description: "Larger of the two values. If only one operand is NaN the other one is returned.",
        example: `fmax.${precision} fa0, fa0, fa1`, encoding: fp("00101", precision, {funct3: "001"})},
      {mnemonic: `fsgnj.${precision}`, syntax: `fsgnj.${precision} rd, rs1, rs2`, name: `Sign inject, ${label}`,
        operation: "f[rd] ← |f[rs1]| with the sign of f[rs2]",
        description: `Takes the magnitude of rs1 and the sign of rs2. With rs1 = rs2 it is a register copy (fmv.${precision}).`,
        example: `fsgnj.${precision} fa0, fa1, fa1   # fmv.${precision} fa0, fa1`, encoding: fp("00100", precision, {funct3: "000"}), see: [`fmv.${precision}`]},
      {mnemonic: `fsgnjn.${precision}`, syntax: `fsgnjn.${precision} rd, rs1, rs2`, name: `Sign inject negated, ${label}`,
        operation: "f[rd] ← |f[rs1]| with the opposite sign of f[rs2]",
        description: `Takes the magnitude of rs1 and the opposite of rs2's sign. With rs1 = rs2 it negates (fneg.${precision}).`,
        example: `fsgnjn.${precision} fa0, fa1, fa1  # fneg.${precision} fa0, fa1`, encoding: fp("00100", precision, {funct3: "001"}), see: [`fneg.${precision}`]},
      {mnemonic: `fsgnjx.${precision}`, syntax: `fsgnjx.${precision} rd, rs1, rs2`, name: `Sign inject XOR, ${label}`,
        operation: "f[rd] ← |f[rs1]| with sign(rs1) XOR sign(rs2)",
        description: `XORs the two signs. With rs1 = rs2 the sign becomes positive: the absolute value (fabs.${precision}).`,
        example: `fsgnjx.${precision} fa0, fa1, fa1  # fabs.${precision} fa0, fa1`, encoding: fp("00100", precision, {funct3: "010"}), see: [`fabs.${precision}`]},
      {mnemonic: `feq.${precision}`, syntax: `feq.${precision} rd, rs1, rs2`, name: `Compare equal, ${label}`,
        operation: "x[rd] ← (f[rs1] == f[rs2]) ? 1 : 0",
        description: "Writes 1 to the integer register rd when the values are equal. Any NaN operand gives 0. Branch on the result with bnez / beqz.",
        example: `feq.${precision} t0, fa0, fa1\nbnez t0, same`, encoding: fp("10100", precision, {funct3: "010"})},
      {mnemonic: `flt.${precision}`, syntax: `flt.${precision} rd, rs1, rs2`, name: `Compare less than, ${label}`,
        operation: "x[rd] ← (f[rs1] < f[rs2]) ? 1 : 0",
        description: "Writes 1 to the integer register rd when rs1 < rs2. A NaN operand gives 0 and sets the invalid flag. There is no fgt: swap the operands.",
        example: `flt.${precision} t0, fa0, fa1`, encoding: fp("10100", precision, {funct3: "001"})},
      {mnemonic: `fle.${precision}`, syntax: `fle.${precision} rd, rs1, rs2`, name: `Compare less or equal, ${label}`,
        operation: "x[rd] ← (f[rs1] ≤ f[rs2]) ? 1 : 0",
        description: "Writes 1 to the integer register rd when rs1 ≤ rs2. A NaN operand gives 0 and sets the invalid flag. There is no fge: swap the operands.",
        example: `fle.${precision} t0, fa0, fa1`, encoding: fp("10100", precision, {funct3: "000"})},
      {mnemonic: `fclass.${precision}`, syntax: `fclass.${precision} rd, rs1`, name: `Classify, ${label}`,
        operation: "x[rd] ← one-hot class of f[rs1]",
        description: "Sets exactly one bit of rd: 0 −∞, 1 negative normal, 2 negative subnormal, 3 −0, 4 +0, 5 positive subnormal, 6 positive normal, 7 +∞, 8 signaling NaN, 9 quiet NaN.",
        example: `fclass.${precision} t0, fa0`, encoding: fp("11100", precision, {rs2: "00000", funct3: "001"})},
      {mnemonic: `fcvt.w.${precision}`, syntax: `fcvt.w.${precision} rd, rs1[, rm]`, name: `Convert ${label} to signed integer`,
        operation: "x[rd] ← int32(f[rs1])",
        description: "Converts to a signed 32-bit integer. It rounds with the current mode (to nearest by default), not by truncation: add `, rtz` to truncate like a C cast. Out-of-range values saturate.",
        example: `fcvt.w.${precision} t0, fa0, rtz   # t0 = (int) fa0`, encoding: fp("11000", precision, {rs2: "00000"}), see: [`fcvt.${precision}.w`, "fmv.x.w"]},
      {mnemonic: `fcvt.wu.${precision}`, syntax: `fcvt.wu.${precision} rd, rs1[, rm]`, name: `Convert ${label} to unsigned integer`,
        operation: "x[rd] ← uint32(f[rs1])",
        description: "Converts to an unsigned 32-bit integer, rounding with the current mode unless an rm such as rtz is given. Negative values become 0.",
        example: `fcvt.wu.${precision} t0, fa0, rtz`, encoding: fp("11000", precision, {rs2: "00001"}), see: [`fcvt.${precision}.wu`]},
      {mnemonic: `fcvt.${precision}.w`, syntax: `fcvt.${precision}.w rd, rs1`, name: `Convert signed integer to ${label}`,
        operation: "f[rd] ← float(x[rs1] as signed)",
        description: "Converts the signed integer in rs1 to a floating-point value.",
        example: `fcvt.${precision}.w fa0, t0`, encoding: fp("11010", precision, {rs2: "00000"}), see: [`fcvt.w.${precision}`, "fmv.w.x"]},
      {mnemonic: `fcvt.${precision}.wu`, syntax: `fcvt.${precision}.wu rd, rs1`, name: `Convert unsigned integer to ${label}`,
        operation: "f[rd] ← float(x[rs1] as unsigned)",
        description: "Converts the unsigned integer in rs1 to a floating-point value.",
        example: `fcvt.${precision}.wu fa0, t0`, encoding: fp("11010", precision, {rs2: "00001"}), see: [`fcvt.wu.${precision}`]}
    ]),
    {mnemonic: "fcvt.s.d", extension: "D", syntax: "fcvt.s.d rd, rs1[, rm]", name: "Convert double to single",
      operation: "f[rd] ← single(f[rs1])",
      description: "Rounds a double-precision value to single precision.",
      example: "fcvt.s.d fa0, fa1", encoding: fp("01000", "s", {rs2: "00001"}), see: ["fcvt.d.s"]},
    {mnemonic: "fcvt.d.s", extension: "D", syntax: "fcvt.d.s rd, rs1", name: "Convert single to double",
      operation: "f[rd] ← double(f[rs1])",
      description: "Widens a single-precision value to double precision. It is always exact.",
      example: "fcvt.d.s fa0, fa1", encoding: fp("01000", "d", {rs2: "00000"}), see: ["fcvt.s.d"]},

    // ---- Pseudo-instructions ----
    pseudo("nop", "nop", "No operation", "addi x0, x0, 0",
      "Does nothing for one instruction slot. Handy to pad code or to see a bubble in the pipeline view."),
    pseudo("li", "li rd, imm", "Load immediate", "addi rd, x0, imm\n# or, when imm does not fit in 12 bits:\nlui rd, %hi(imm)\naddi rd, rd, %lo(imm)",
      "Loads any 32-bit constant. The assembler uses a single addi when the value fits in −2048…2047, otherwise lui + addi.",
      "li t0, 100000"),
    pseudo("la", "la rd, symbol", "Load address", "auipc rd, %pcrel_hi(symbol)\naddi rd, rd, %pcrel_lo(symbol)",
      "Loads the address of a label, such as an array in .data.", "la a0, vector"),
    pseudo("mv", "mv rd, rs", "Copy register", "addi rd, rs, 0", "Copies rs into rd.", "mv a0, t0"),
    pseudo("not", "not rd, rs", "Bitwise NOT", "xori rd, rs, -1", "Inverts every bit (one's complement).", "not t0, t1"),
    pseudo("neg", "neg rd, rs", "Negate", "sub rd, x0, rs", "Two's-complement negation: rd = −rs.", "neg t0, t1"),
    pseudo("seqz", "seqz rd, rs", "Set if equal to zero", "sltiu rd, rs, 1", "rd = 1 when rs is zero, otherwise 0.", "seqz t0, a0"),
    pseudo("snez", "snez rd, rs", "Set if not zero", "sltu rd, x0, rs", "rd = 1 when rs is not zero, otherwise 0.", "snez t0, a0"),
    pseudo("sltz", "sltz rd, rs", "Set if less than zero", "slt rd, rs, x0", "rd = 1 when rs is negative.", "sltz t0, a0"),
    pseudo("sgtz", "sgtz rd, rs", "Set if greater than zero", "slt rd, x0, rs", "rd = 1 when rs is positive.", "sgtz t0, a0"),
    pseudo("zext.b", "zext.b rd, rs", "Zero-extend byte", "andi rd, rs, 255", "Keeps only the lowest 8 bits.", "zext.b t0, a0"),
    pseudo("beqz", "beqz rs, label", "Branch if zero", "beq rs, x0, label", "Branches when rs is zero.", "beqz t0, done"),
    pseudo("bnez", "bnez rs, label", "Branch if not zero", "bne rs, x0, label", "Branches when rs is not zero.", "bnez t0, loop"),
    pseudo("blez", "blez rs, label", "Branch if ≤ zero", "bge x0, rs, label", "Branches when rs ≤ 0 (signed).", "blez a0, skip"),
    pseudo("bgez", "bgez rs, label", "Branch if ≥ zero", "bge rs, x0, label", "Branches when rs ≥ 0 (signed).", "bgez a0, positive"),
    pseudo("bltz", "bltz rs, label", "Branch if < zero", "blt rs, x0, label", "Branches when rs < 0 (signed).", "bltz a0, negative"),
    pseudo("bgtz", "bgtz rs, label", "Branch if > zero", "blt x0, rs, label", "Branches when rs > 0 (signed).", "bgtz a0, positive"),
    pseudo("bgt", "bgt rs, rt, label", "Branch if greater than", "blt rt, rs, label", "Branches when rs > rt (signed). The assembler swaps the operands of blt.", "bgt t0, t1, bigger"),
    pseudo("ble", "ble rs, rt, label", "Branch if less or equal", "bge rt, rs, label", "Branches when rs ≤ rt (signed).", "ble t0, t1, loop"),
    pseudo("bgtu", "bgtu rs, rt, label", "Branch if greater than, unsigned", "bltu rt, rs, label", "Branches when rs > rt (unsigned).", "bgtu t0, t1, bigger"),
    pseudo("bleu", "bleu rs, rt, label", "Branch if less or equal, unsigned", "bgeu rt, rs, label", "Branches when rs ≤ rt (unsigned).", "bleu t0, t1, loop"),
    pseudo("j", "j label", "Jump", "jal x0, label", "Unconditional jump within ±1 MiB; no return address is saved.", "j loop"),
    pseudo("jr", "jr rs", "Jump register", "jalr x0, 0(rs)", "Jumps to the address in rs without saving a return address.", "jr t0"),
    pseudo("ret", "ret", "Return from function", "jalr x0, 0(ra)", "Returns to the address saved in ra by jal / call.", "ret"),
    pseudo("call", "call label", "Call function", "auipc ra, %pcrel_hi(label)\njalr ra, %pcrel_lo(label)(ra)",
      "Calls a function anywhere in the address space and saves the return address in ra. The linker may relax it to a single jal.", "call compute"),
    pseudo("tail", "tail label", "Tail call", "auipc t1, %pcrel_hi(label)\njalr x0, %pcrel_lo(label)(t1)",
      "Jumps to a function without saving a return address, so that function returns straight to our caller. Uses t1 as a scratch register.", "tail compute"),
    ...floatFamily(precision => [
      pseudo(`fmv.${precision}`, `fmv.${precision} rd, rs`, "Copy float register", `fsgnj.${precision} rd, rs, rs`, "Copies a floating-point register.", `fmv.${precision} fa0, ft0`),
      pseudo(`fabs.${precision}`, `fabs.${precision} rd, rs`, "Absolute value", `fsgnjx.${precision} rd, rs, rs`, "rd = |rs|.", `fabs.${precision} fa0, fa0`),
      pseudo(`fneg.${precision}`, `fneg.${precision} rd, rs`, "Negate float", `fsgnjn.${precision} rd, rs, rs`, "rd = −rs.", `fneg.${precision} fa0, fa0`)
    ]),
    pseudo("csrr", "csrr rd, csr", "Read CSR", "csrrs rd, csr, x0", "Reads a control and status register.", "csrr t0, fcsr"),
    pseudo("csrw", "csrw csr, rs", "Write CSR", "csrrw x0, csr, rs", "Writes a control and status register.", "csrw fcsr, t0"),
    pseudo("csrs", "csrs csr, rs", "Set CSR bits", "csrrs x0, csr, rs", "Sets the CSR bits that are 1 in rs.", "csrs fflags, t0"),
    pseudo("csrc", "csrc csr, rs", "Clear CSR bits", "csrrc x0, csr, rs", "Clears the CSR bits that are 1 in rs.", "csrc fflags, t0"),
    pseudo("csrwi", "csrwi csr, uimm", "Write CSR immediate", "csrrwi x0, csr, uimm", "Writes a 5-bit constant to a CSR.", "csrwi frm, 1"),
    pseudo("csrsi", "csrsi csr, uimm", "Set CSR bits immediate", "csrrsi x0, csr, uimm", "Sets CSR bits from a 5-bit constant.", "csrsi fflags, 1"),
    pseudo("csrci", "csrci csr, uimm", "Clear CSR bits immediate", "csrrci x0, csr, uimm", "Clears CSR bits from a 5-bit constant.", "csrci fflags, 31"),
    pseudo("frcsr", "frcsr rd", "Read FP control/status", "csrrs rd, fcsr, x0", "Reads fcsr: the rounding mode (bits 7–5) and the accrued exception flags (bits 4–0).", "frcsr t0"),
    pseudo("fscsr", "fscsr rs", "Write FP control/status", "csrrw x0, fcsr, rs", "Writes fcsr.", "fscsr t0"),
    pseudo("rdcycle", "rdcycle rd", "Read cycle counter", "csrrs rd, cycle, x0", "Reads the low 32 bits of the clock-cycle counter. Two reads around a block of code measure how long it takes.", "rdcycle t0"),
    pseudo("rdcycleh", "rdcycleh rd", "Read cycle counter, high", "csrrs rd, cycleh, x0", "Reads the upper 32 bits of the cycle counter.", "rdcycleh t1"),
    pseudo("rdtime", "rdtime rd", "Read real-time counter", "csrrs rd, time, x0", "Reads the low 32 bits of the wall-clock timer.", "rdtime t0"),
    pseudo("rdinstret", "rdinstret rd", "Read instructions-retired counter", "csrrs rd, instret, x0", "Reads the low 32 bits of the count of completed instructions.", "rdinstret t0"),
    pseudo("rdinstreth", "rdinstreth rd", "Read instructions-retired counter, high", "csrrs rd, instreth, x0", "Reads the upper 32 bits of the count of completed instructions.", "rdinstreth t1"),

    // ---- C: compressed (16-bit) instructions ----
    compressed("c.addi4spn", "CIW", "c.addi4spn rd', nzuimm", "addi rd', sp, nzuimm", "Adds a nonzero multiple of 4 (up to 1020) to sp. Used to form pointers into the stack frame."),
    compressed("c.lw", "CL", "c.lw rd', offset(rs1')", "lw rd', offset(rs1')", "Loads a word; the offset is a multiple of 4 from 0 to 124."),
    compressed("c.sw", "CS", "c.sw rs2', offset(rs1')", "sw rs2', offset(rs1')", "Stores a word; the offset is a multiple of 4 from 0 to 124."),
    compressed("c.flw", "CL", "c.flw rd', offset(rs1')", "flw rd', offset(rs1')", "Loads a single-precision float; the offset is a multiple of 4 from 0 to 124."),
    compressed("c.fsw", "CS", "c.fsw rs2', offset(rs1')", "fsw rs2', offset(rs1')", "Stores a single-precision float; the offset is a multiple of 4 from 0 to 124."),
    compressed("c.fld", "CL", "c.fld rd', offset(rs1')", "fld rd', offset(rs1')", "Loads a double; the offset is a multiple of 8 from 0 to 248.", true),
    compressed("c.fsd", "CS", "c.fsd rs2', offset(rs1')", "fsd rs2', offset(rs1')", "Stores a double; the offset is a multiple of 8 from 0 to 248.", true),
    compressed("c.nop", "CI", "c.nop", "addi x0, x0, 0", "No operation."),
    compressed("c.addi", "CI", "c.addi rd, nzimm", "addi rd, rd, nzimm", "Adds a nonzero 6-bit signed constant (−32 to 31) to rd."),
    compressed("c.jal", "CJ", "c.jal label", "jal ra, label", "Calls a function within ±2 KiB (RV32 only)."),
    compressed("c.li", "CI", "c.li rd, imm", "addi rd, x0, imm", "Loads a 6-bit signed constant (−32 to 31)."),
    compressed("c.addi16sp", "CI", "c.addi16sp sp, nzimm", "addi sp, sp, nzimm", "Adjusts sp by a nonzero multiple of 16 (−512 to 496): allocating and freeing stack frames."),
    compressed("c.lui", "CI", "c.lui rd, nzimm", "lui rd, nzimm", "Loads a nonzero 6-bit signed constant into bits 17–12; rd cannot be x0 or sp."),
    compressed("c.srli", "CB", "c.srli rd', shamt", "srli rd', rd', shamt", "Logical right shift by 1 to 31."),
    compressed("c.srai", "CB", "c.srai rd', shamt", "srai rd', rd', shamt", "Arithmetic right shift by 1 to 31."),
    compressed("c.andi", "CB", "c.andi rd', imm", "andi rd', rd', imm", "AND with a 6-bit signed constant."),
    compressed("c.sub", "CA", "c.sub rd', rs2'", "sub rd', rd', rs2'", "Subtracts rs2' from rd'."),
    compressed("c.xor", "CA", "c.xor rd', rs2'", "xor rd', rd', rs2'", "XORs rs2' into rd'."),
    compressed("c.or", "CA", "c.or rd', rs2'", "or rd', rd', rs2'", "ORs rs2' into rd'."),
    compressed("c.and", "CA", "c.and rd', rs2'", "and rd', rd', rs2'", "ANDs rs2' into rd'."),
    compressed("c.j", "CJ", "c.j label", "jal x0, label", "Jumps within ±2 KiB."),
    compressed("c.beqz", "CB", "c.beqz rs1', label", "beq rs1', x0, label", "Branches within ±256 bytes when rs1' is zero."),
    compressed("c.bnez", "CB", "c.bnez rs1', label", "bne rs1', x0, label", "Branches within ±256 bytes when rs1' is not zero."),
    compressed("c.slli", "CI", "c.slli rd, shamt", "slli rd, rd, shamt", "Left shift by 1 to 31."),
    compressed("c.lwsp", "CI", "c.lwsp rd, offset(sp)", "lw rd, offset(sp)", "Loads a word from the stack; the offset is a multiple of 4 from 0 to 252."),
    compressed("c.flwsp", "CI", "c.flwsp rd, offset(sp)", "flw rd, offset(sp)", "Loads a single-precision float from the stack."),
    compressed("c.fldsp", "CI", "c.fldsp rd, offset(sp)", "fld rd, offset(sp)", "Loads a double from the stack; the offset is a multiple of 8 from 0 to 504.", true),
    compressed("c.jr", "CR", "c.jr rs1", "jalr x0, 0(rs1)", "Jumps to the address in rs1. `c.jr ra` is the compressed ret."),
    compressed("c.mv", "CR", "c.mv rd, rs2", "add rd, x0, rs2", "Copies rs2 into rd."),
    compressed("c.ebreak", "CR", "c.ebreak", "ebreak", "Breakpoint."),
    compressed("c.jalr", "CR", "c.jalr rs1", "jalr ra, 0(rs1)", "Calls the function whose address is in rs1."),
    compressed("c.add", "CR", "c.add rd, rs2", "add rd, rd, rs2", "Adds rs2 to rd."),
    compressed("c.swsp", "CSS", "c.swsp rs2, offset(sp)", "sw rs2, offset(sp)", "Stores a word on the stack; the offset is a multiple of 4 from 0 to 252."),
    compressed("c.fswsp", "CSS", "c.fswsp rs2, offset(sp)", "fsw rs2, offset(sp)", "Stores a single-precision float on the stack."),
    compressed("c.fsdsp", "CSS", "c.fsdsp rs2, offset(sp)", "fsd rs2, offset(sp)", "Stores a double on the stack; the offset is a multiple of 8 from 0 to 504.", true),

    // ---- Assembler directives ----
    directive(".text", ".text", "Code section", "Switches to the section that holds instructions."),
    directive(".data", ".data", "Data section", "Switches to the section for initialized, writable variables and arrays.",
      ".data\nvector: .word 1, 2, 3, 4"),
    directive(".rodata", ".section .rodata", "Read-only data section", "Switches to the section for constants that the program never writes."),
    directive(".bss", ".bss", "Zero-initialized section", "Switches to the section for variables that start at zero. It takes no space in the program file.",
      ".bss\nbuffer: .space 64"),
    directive(".section", ".section name[, flags]", "Select a section", "Switches to the named section, for example .text, .data or .rodata."),
    directive(".globl", ".globl symbol", "Export a symbol", "Makes a label visible to the linker. Every program exports _start, where execution begins. `.global` is a synonym.",
      ".globl _start"),
    directive(".word", ".word value[, value…]", "32-bit values", "Emits one or more 32-bit integers (or label addresses).",
      "table: .word 10, -3, 0x7fffffff"),
    directive(".half", ".half value[, value…]", "16-bit values", "Emits one or more 16-bit integers. `.short` is a synonym.", "values: .half 1, 2, 3"),
    directive(".byte", ".byte value[, value…]", "8-bit values", "Emits one or more bytes.", "bytes: .byte 0x10, 0x20, 'A'"),
    directive(".float", ".float value[, value…]", "Single-precision values", "Emits one or more 32-bit IEEE 754 floats.", "coeff: .float 1.5, -0.25"),
    directive(".double", ".double value[, value…]", "Double-precision values", "Emits one or more 64-bit IEEE 754 doubles. Align to 8 bytes first with .align 3.", ".align 3\npi: .double 3.141592653589793"),
    directive(".space", ".space size[, fill]", "Reserve bytes", "Reserves size bytes, filled with zero (or with fill). `.zero size` is equivalent.", "result: .space 40     # room for 10 words"),
    directive(".align", ".align n", "Align to 2ⁿ", "Pads with zeros until the location counter is a multiple of 2ⁿ bytes. `.align 2` gives 4-byte alignment for words.", ".align 2"),
    directive(".balign", ".balign bytes", "Align to a byte count", "Pads until the location counter is a multiple of the given number of bytes.", ".balign 8"),
    directive(".ascii", ".ascii \"text\"", "String without terminator", "Emits the characters of a string with no terminating zero byte.", "msg: .ascii \"Hi\""),
    directive(".asciz", ".asciz \"text\"", "Zero-terminated string", "Emits the characters of a string followed by a zero byte, like a C string. `.string` is a synonym.", "msg: .asciz \"Hello\\n\""),
    directive(".equ", ".equ name, value", "Define a constant", "Gives a name to a constant value; it uses no memory. `.set` is a synonym.", ".equ N, 10\nli t0, N")
  ];

  function floatFamily(build) {
    return [["s", "single precision", "F"], ["d", "double precision", "D"]].flatMap(([precision, label, extension]) =>
      build(precision, label).map(entry => ({extension, needsDouble: precision === "d", ...entry})));
  }

  function pseudo(mnemonic, syntax, name, expansion, description, example = syntax) {
    return {mnemonic, extension: "Pseudo", syntax, name, expansion, description, example};
  }

  function compressed(mnemonic, format, syntax, expansion, description, double = false) {
    return {mnemonic, extension: "C", syntax, name: `Compressed ${expansion.split(" ")[0]}`, expansion,
      description: description + (syntax.includes("'") ? " Primed registers (rd', rs1', rs2') must be one of x8–x15 (s0, s1, a0–a5, or fs0, fs1, fa0–fa5)." : ""),
      example: syntax, encoding: {format, compressed: true}, needsDouble: double};
  }

  function directive(mnemonic, syntax, name, description, example = syntax) {
    return {mnemonic, extension: "Directive", syntax, name, description, example};
  }

  return entries;
})();
